### ISSUE TITLE
docs: nsqd HTTP API doc suggestions

### ISSUE THREAD

**Issue by mccutchen** [bitly/nsq#487]
I was just poking around in the docs to try to figure out the best way to programmatically pause/unpause a topic during a deploy, and it took a bit of trial-and-error to figure out the right invocation of `curl` to accomplish what I wanted.

I think these changes would have made it a bit more straightforward:

 - [x] **note HTTP method along with URL** — I initially just tried making a `GET` and only figured I should try a `POST` when I saw the `HTTP 405` response
 - [x] **note that params must be *query* params** — when switching to a `POST`, I figured I should probably send a the `topic=foo` param as the body (ie, `curl -d 'topic=foo' localhost:4151/topic/pause'`), but it turns out that they have to be sent in the query string.
 - [x] **maybe add a `curl` example for each endpoint?** — not sure if this is overkill

I'd be happy to take a shot at making these updates if y'all think they're appropriate.

**Comment by mreiferson** [comment]
updated http://nsq.io/components/nsqd.html

**Comment by mccutchen** [comment]
:fire: :fire: :fire:
