### ISSUE TITLE
Topic hierarchy support

### ISSUE THREAD

**Issue by khash** [bitly/nsq#525]
Is it possible to have topic hierarchy? For example a message to `test` will be published to `test`, `test/abc` and `test/abc/xyz`

This is similar to Faye support for channel hierarchy. It could also be achieved by regex topic names.

**Comment by mreiferson** [comment]
Hi @khash, there is no built-in support for this but you might be able to achieve something similar by using channels for a topic, which each receive a copy of the message for that topic (i.e. pubsub).
