### ISSUE TITLE
nsqd: add Uptime or StartTime to ApiResponse

### ISSUE THREAD

**Issue by twmb** [bitly/nsq#533]
Adding an uptime field to nsqd's ApiResponse would allow an nsqd monitor to detect unexpected restarts, as would StartTime.

I would use uptime more, but others might use start time for other reasons. Although one can be calculated from the other, sending both uptime and start time in the json response would make it easer for both uptime consumers and start time consumers.

I propose sending uptime as an int32 in seconds because most languages have functions that process time in seconds. Also, nanoseconds would not be a good idea because json cannot handle int64's, unless these ints are wrapped in strings.

**Comment by mreiferson** [comment]
yea, this is a great idea...

I'm assuming you mean `/stats`, right?

**Comment by twmb** [comment]
Yes.

 @stephensearles had a good point in IRC that StartTime is great because it allows one to detect a restart if the value changes at all. Because of this, I'm not so sure "uptime" is necessary.

**Comment by mreiferson** [comment]
let's start with `start_time`!

**Comment by ShawnSpooner** [comment]
Were you thinking a response along these lines?
For JSON:

    {"status_code":200,"status_txt":"OK","data":{"version":"0.3.3 alpha","health":"OK","start_time":1424565254,"topics":[]}}

And for text:
```
nsqd v0.3.3-alpha (built w/go1.4)
start_time 1424565254

NO_TOPICS
```

**Comment by mreiferson** [comment]
JSON looks good, for text it would be nice to show a human readable date-time, right?

**Comment by mreiferson** [comment]
... and a duration

**Comment by ShawnSpooner** [comment]
I think that is a great idea. Do you have a preferred format? Would RFC822("02 Jan 06 15:04 MST") be sufficient? For duration, are you thinking a total uptime?

**Comment by mreiferson** [comment]
Didn't have a preference for any particular format - just something readable!

For duration, yes, total uptime (this is pretty easy, Go's `time.Duration` can `String()` itself)

**Comment by twmb** [comment]
Duration's .String will print 1m2s, which will make it hard to consume in
other languages?

**Comment by mreiferson** [comment]
@twmb he was asking about the test format, the JSON format will be an integer

**Comment by mreiferson** [comment]
see #547
