### ISSUE TITLE
docker: no "latest" tag

### ISSUE THREAD

**Issue by paddyforan** [bitly/nsq#542]
When a version is omitted in docker (e.g. `docker pull nsqio/nsq`) it uses the `:latest` tag. I was hoping the docker registry would be smart enough to know the last pushed image was the "latest" image, but I was apparently wrong about that:

```sh
$ docker pull nsqio/nsq
Pulling repository nsqio/nsq
FATA[0002] Tag latest not found in repository nsqio/nsq
```

Two step solution:

1. If nobody objects, I can just tag the current v0.3.2 image as the "latest" image, and push it. That solves the problem immediately.
2. For the future, I can add a step to the `dist.sh` script that will tag the image as the latest image, as well as tagging it as the version number. That solves the problem in future releases.

Any objection to either of these?

**Comment by paddyforan** [comment]
After some discussion in IRC, I've executed the first step. The next step is basically adding `docker tag nsqio/nsq:v$VERSION nsqio/nsq:latest` to the `dist.sh` script after we build the image. I'll get a PR in for that.

**Comment by jibinashraf** [comment]
What is i`m using a private repository ?

**Comment by paddyforan** [comment]
@jibinashraf I'm not sure I understand the question. Can you elaborate?

**Comment by jibinashraf** [comment]
I`m using a private docker registry. I have pushed an image from one pc and trying to pull it from another PC. I`m getting teh error : FATA[0001] Tag latest not found in repository

**Comment by jibinashraf** [comment]
How to change the tag in my docker registry. (I would like to have the option of pushing the image again as a last resort since the image is around 4 gigs )

**Comment by paddyforan** [comment]
This is about the [NSQ docker image](https://registry.hub.docker.com/u/nsqio/nsq) specifically. If you need help with Docker itself, I suggest the [Docker repo](https://github.com/docker/docker).
