### ISSUE TITLE
nsqd: cluster test fails

### ISSUE THREAD

**Issue by cespare** [bitly/nsq#551]
On master right now:

```
$ go test github.com/bitly/nsq/nsqd/test
--- FAIL: TestNsqdToLookupd (0.00s)
        cluster_test.go:20: cluster_test.go:33:

                        exp: <nil>

                        got: &url.Error{Op:"Post", URL:"http://127.0.0.1:4151/topic/create?topic=cluster_test1424902718", Err:(*net.OpError)(0xc20804c940)}

FAIL
FAIL    github.com/bitly/nsq/nsqd/test  0.004s
```

**Comment by jehiah** [comment]
@cespare some of the tests are specifically expected to be run via `test.sh` in the repo which spins up a background `nsqd` and `nsqlookupd` to run integration tests against. This is one of those.

Can you confirm that it runs via `test.sh` ?

**Comment by cespare** [comment]
@jehiah thanks. This test does pass with `test.sh.
