### ISSUE TITLE
nsq_to_{nsq,http} hostpool: Use hostpool.NewEpsilonGreedy

### ISSUE THREAD

**Issue by twmb** [bitly/nsq#559]
go-hostpool's default hostpool returns hosts via round robin, with backoff on hosts that fail. The only difference between nsq_to_*'s round robin flag and hostpool's round robin selection is that hostpool also includes backoff on hosts that fail a message.

I propose:
- nsq_to_*'s mode round-robin use `hostpool.New(destNsqdTCPAddrs)`, which would keep the current round robin behavior but also add backoff functionality on hosts that fail messages
- nsq_to_*'s mode hostpool use `hostpool.NewEpsilonGreedy(destNsqdTCPAddrs, 0, &hostpool.LinearEpsilonValueCalculator{})`, which will select hosts based on which host has been most performant in the past.

**Comment by mreiferson** [comment]
@twmb I don't want to change `round-robin` (that's why mode `hostpool` exists).  I would accept a PR that _adds_ a new `epsilon-greedy` mode.

**Comment by mreiferson** [comment]
Discussed in IRC - change the default mode to `hostpool`, leave `round-robin alone, and add `epsilon-greedy` mode.

**Comment by mreiferson** [comment]
fixed in #562
