### ISSUE TITLE
Unsafe dependecy: code.google.com/p/snappy-go/snappy

### ISSUE THREAD

**Issue by larsth** [bitly/nsq#563]
NSQ has a dependency on "code.google.com/p/snappy-go/snappy      12e4b4183793ac4b061921e7980845e750679fd0", but Google will shutdown code.google.com

Edit:
http://google-opensource.blogspot.dk/2015/03/farewell-to-google-code.html

**Comment by mreiferson** [comment]
Interesting, thanks.  Looks like there's a copy available at https://github.com/VividCortex/snappy-go

**Comment by mreiferson** [comment]
fixed in #573
