### ISSUE TITLE
[nsqadmin] Topics occasionally missing producers & client connections

### ISSUE THREAD

**Issue by jamesfzhang** [bitly/nsq#564]
In `nsqadmin`, the page for a topic occasionally shows the "No producers exist for this topic" and "No channels exist for this topic." Sometimes, a subset of `nsqd` hosts appear in the list of producers for that topic. If you refresh the topic's page a few times, the full set of `nsqd` hosts appear. On the nodes page, all 3 `nsqd` hosts appear every time.

I can't quite nail down a pattern. I initially thought maybe HAProxy was round robining me to a `nsqadmin` that somehow fell out of the loop but I went onto one of the servers running nsq locally and reproduced the problem.

Our current set up is 3 servers, each running `nsqd`, `nsqlookupd`, and `nsqadmin`. Each `nsqd` and `nsqadmin` is initialized with all 3 `nsqlookdup` IPs. Currently running v0.3.0. Any ideas?

**Comment by jehiah** [comment]
The confusion caused when there are connection issues is captured in #421 

Are any of your hosts particularly loaded?

**Comment by jamesfzhang** [comment]
Ahh, that makes sense. Yes, all three of them are backed up sizably, some worse than others.

**Comment by mreiferson** [comment]
going to close this in favor of #421
