### ISSUE TITLE
What units is the nsq_to_file -rotate-interval option in?

### ISSUE THREAD

**Issue by godber** [bitly/nsq#568]
What units is the `-rotate-interval` option in for `nsq_to_file`?

I don't know go but it appears to directly compare the output of `time.Since` with the provided argument, see:

https://github.com/bitly/nsq/blob/77a46dbed43cbf8fc1184563300430bdd9200744/apps/nsq_to_file/nsq_to_file.go#L239) 

Is it Nanoseconds?

* http://golang.org/pkg/time/#Since
* http://golang.org/pkg/time/#Duration

Some examples make it look like Go works magic with times.

**Comment by mreiferson** [comment]
https://github.com/bitly/nsq/blob/77a46dbed43cbf8fc1184563300430bdd9200744/apps/nsq_to_file/nsq_to_file.go#L45

It's a `time.Duration` and the flag accepts anything valid for http://golang.org/pkg/time/#ParseDuration
