### ISSUE TITLE
Does NSQ use nsqlookup to transmit data between two nsqd?

### ISSUE THREAD

**Issue by FindNemo** [bitly/nsq#570]
In my house there runs a nsqd and client app "A", they connect each other with http.
In my office there runs another nsqd and another client app "B", they connect each other with http too.
In digitalocean vps there runs a nsqlookup.

"A" registers a topic "test", then "B" send data to "test" topic. This is my questions:

**Does the data will be transmited like "B"->VPS->"A"? or "B" -> "A"?   I means data but not new message notify.**

If  the data transmit path is "B" -> "A", there is anoter quetion:

__when "A" and "B" don't have public IP, "A" and "B" can't send data to each other by TCP, then how nsq works?__

Thank you!

**Comment by mreiferson** [comment]
Answered on the mailing list:

https://groups.google.com/forum/?nomobile=true#!topic/nsq-users/iSDzQBheRN4
