### ISSUE TITLE
nsq_to utility

### ISSUE THREAD

**Issue by ashaffer** [bitly/nsq#574]
I think it would be nice to have an nsq_to utility, that pipes messages to stdout.  This would make it easy to create small, composable utilities that can accept messages from other sources.  E.g.

`nsq_to --channel processor | process_events`

Then doing the same from a set of logs is as simple as:

`cat logs/* | process_events`

It would also probably be useful to have an `nsq_finished` command to go with these, so that the intermediate processor may output event id's that have been successfully processed.  That second part may be more application-specific, but I think the `nsq_to` at least might have a pretty broad appeal.

**Comment by jehiah** [comment]
@ashaffer there actually **is** a utility included that writes messages to stdout. That utility is [`nsq_tail`](http://nsq.io/components/utilities.html#nsqtail). 

There are certain obvious drawbacks of that processing method in terms of poor message reliability beyond the stdout pipe, but as you mentioned, for many things it can be convenient and more than sufficient. 

In terms of event ID's i highly recommend messages be structured to contain a message ID (and timestamp, etc) and not rely on the NSQ internal message ID's.
