### ISSUE TITLE
Please separate logger levels.

### ISSUE THREAD

**Issue by fjjiaboming** [bitly/nsq#581]
Logger is too busy.
Our scenario is PHP <--short connection--> NSQd so that the conns is very frequent.
`
[nsqd] 2015/05/05 09:59:51.890518 TCP: new client(...:45582)
[nsqd] 2015/05/05 09:59:51.890580 CLIENT(...:45582): desired protocol magic '  V2'
[nsqd] 2015/05/05 09:59:51.893928 PROTOCOL(V2): [...:45582] exiting ioloop
[nsqd] 2015/05/05 09:59:51.893984 ERROR: client(...:45582) - failed to read command - EOF
[nsqd] 2015/05/05 09:59:51.894037 PROTOCOL(V2): [...:45582] exiting messagePump
`

**Comment by fjjiaboming** [comment]
Could you accept our patches for adding logger feature?

**Comment by jehiah** [comment]
@fjjiaboming can you describe a little more about your need for short connections? Are you using that for publishing messages to nsqd?

**Comment by fjjiaboming** [comment]
describe a little more about our need ?    It is on production. 

Yes.  PHP publishes msg to NSQd.
`
Are you using that for publishing messages to nsqd?
`

**Comment by jehiah** [comment]
Why are your connections short lived? Nsqd expects long lived TCP connections.

If you need short connections, can you publish to nsqd through HTTP [`/pub`](http://nsq.io/components/nsqd.html#pub) endpoint?

**Comment by fjjiaboming** [comment]
Because of php-fpm model . 
It produces too many connections. If 500~2K connections in one host , then we have many host of PHP web and NSQd can't accept the pressure .

**Comment by fjjiaboming** [comment]
Focus on logger level . 
If I do a patch , is it OK ? 
Actually , I do not like to fork the master to maintain the upgrade and merge ...

**Comment by mreiferson** [comment]
@fjjiaboming thanks for opening up this issue.

IMO the logs are a symptom, not a problem (also, it's far more expensive anyway for `nsqd` to have to open new connections each time).

Try restructuring things such that you maintain a pool of long lived connections in your process that PUBs.

I don't think, under normal operation, that `nsqd` logs are overwhelming and I don't want to encourage ways to reduce them. When issues arise they are invaluable for debugging.

**Comment by fjjiaboming** [comment]
@mreiferson I suggest that NSQ uses  seelog  prefer to log4go. 
It is convenient !
