### ISSUE TITLE
Auto-scaling producers: fastest consumer hoovers all the messages?

### ISSUE THREAD

**Issue by rprieto** [bitly/nsq#588]
Hi,

We've been trialling NSQ (with great success) but there's one thing we can't seem to figure out in an auto-scaling environment. Do you mind explaining what we're missing - or how NSQ supports this?

- Producer A produces messages `m`, and has 2 connected consumers

```
Producer A
    - channel X [m m m m]   ---------------------  Consumer X
    - channel Y [m m m m]   ---------------------  Consumer Y
```

- Producer needs to scale, and new node starts emitting messages

```
Producer A
    - channel X [m m m m]   ---------------------  Consumer X
    - channel Y [m m m m]   ---------------------  Consumer Y

Producer B
    - topic [m m m m]      # stored at the topic level since there are no consumers
```

- Consumer X heartbeats to the lookup first, and connects to Producer B. A channel gets created, and all messages get transferred to that channel.

```
Producer A
    - channel X [m m m m]   ---------------------  Consumer X
    - channel Y [m m m m]   ---------------------  Consumer Y

Producer B
    - channel X [m m m m]   ---------------------  Consumer X
```

- Consumer Y heartbeats to the lookup, and connects to Producer B. No messages are available to be read yet.

```
Producer A
    - channel X [m m m m]   ---------------------  Consumer X
    - channel Y [m m m m]   ---------------------  Consumer Y

Producer B
    - channel X [m m m m]   ---------------------  Consumer X
    - channel Y [       ]   ---------------------  Consumer Y
```

We understand that consumers can't get messages issued "in the past". What we want to solve here though is the following:

- when producers spin up, is there a timeframe until all consumers have heart-beated where messages will only be delivered to a subset of consumers
- which consumers get the messages seems to be indeterministic, depending on who heartbeats first

Did we understand the logic right, and is this a limitation of NSQ being a distributed system? We thought of a few ways we could "pre-warm" the producers and create channels in advance, but haven't found a nice way to do this without adding extra coupling.

Cheers

**Comment by jehiah** [comment]
@rprieto When nsqd is configured to use `nsqlookupd` it will do a channel discovery call to nsqlookupd to discover existing channels in this case. This means that when the first message is sent to the topic on `Producer B` in your scenario, it will query `nsqlokupd` for that topic, discover channels `X` and `Y`, and queue the message to both.

Does that help?

**Comment by rprieto** [comment]
Hi @jehiah. This is exactly what we're after and it makes a lot of sense. Thanks for a very fast reply!
