### ISSUE TITLE
Any plan to support data-node HA?

### ISSUE THREAD

**Issue by fjjiaboming** [bitly/nsq#589]
NSQ supports HA ? 
Replication(Master-Slave) or Replication(Backup) or ...

**Comment by mreiferson** [comment]
there's been on ongoing design discussion about potential implementations...

https://docs.google.com/document/d/1vxPKbLYckD80OiG9CxTWZufB4lv0b3hGZy4C9yBmI_k/edit

**Comment by git-hulk** [comment]
hi @mreiferson,  when this feature would be published or developed. We want to use nsq, and need to prevent message lost. 

Thanks for your excellent work. : )
