### ISSUE TITLE
Limit requeue count

### ISSUE THREAD

**Issue by fizerkhan** [bitly/nsq#591]
When i processed a queue, it failed in between. Then It requeued and failed and requeued again. It happens continuously. Unfortunately in my case, i am sending a mail :(. I want to set requeue limit so that the message will not requeued after certain number of retry.

Is there any option to do it?

**Comment by jehiah** [comment]
@fizerkhan this is a good question for the [mailing list](https://groups.google.com/forum/#!forum/nsq-users)

The specific's depend on what client library you are using, but in general there are details exposed about the [number of attempts](http://godoc.org/github.com/bitly/go-nsq#Message.Attempts) on a message, and [configurables](http://godoc.org/github.com/bitly/go-nsq#Config.MaxAttempts) to set the threshold where messages are "given up" on (which essentially just amounts to immediately telling nsq you are done with a message and not processing it any further).

**Comment by fizerkhan** [comment]
Thanks @jehiah
