### ISSUE TITLE
Wrong guid generation

### ISSUE THREAD

**Issue by ikkeps** [bitly/nsq#592]
In production we suddenly expiriencing lots of message duplication messages with about hundred of nsqd nodes. After looking at the code we realized that guid was improperly generated for worker ids >= 1024. see https://github.com/bitly/nsq/blob/master/nsqd/guid.go#L19 . Worker id has range 0-4095, while there are only ten bits shift between it and timestamp.

**Comment by jehiah** [comment]
@ikkeps you are correct that there is/was an issue with values > 1024. That's been fixed in #586

**Comment by ikkeps** [comment]
Oh, sorry, did not noticed that. Thanks for such fast reply!
