### ISSUE TITLE
How to properly shutdown a consumer

### ISSUE THREAD

**Issue by kesutton** [bitly/nsq#604]
Not an issue, just a question.

Consider the following:

There are 10,000 messages queued in NSQd topic "topic1".  A single consumer comes along, and subscribes to that topic with a single connection.  Let's say the ready count is set to 2,000, and it takes the consumer 1 second to process each message, before calling FIN.

Immediately after subscription, the 10,000 messages are all drained in the consumer's channel queue, and 2,000 messages are sent out to the consumer, and stored in whatever queue the nsq client library uses.  So the channel queue is no 8,000.  The client library feeds the consumer messages, and then calls FIN when the consumer acknowledges it is finished, always taking one second.  So for example, after 30 seconds, the 30 messages have been FIN'd, the channel queue is now 7,970, and the client library still has 2,000 queued messages.

Let's say the consumer is shutdown at exactly 30 seconds.  When a shutdown occurs, the consumer first calls CLS, which means "Cleanly close your connection (no more messages are sent)" (from the docs http://nsq.io/clients/tcp_protocol_spec.html).  However, there are still 2,000 messages in the client library's internal queue.  If the consumer's shutdown routine allows it to finish consuming all queued messages, then it will still continue to call FIN.  However, I believe that the CLS operation has completely severed the connection to NSQ (so "messages" in the docs means all kinds of NSQ messages, not actual data messages), and those FINs go unreceived.  So now the consumer has handled 2,000 unacknowledged messages, meaning NSQ will requeue those messages after its own timeout, and send them again when the consumer reconnects.

I understand NSQ suggests (requires) consumers to handle messages in an idempotent fashion, but is there any series of steps to have NSQ stop sending messages, but maintain the ability to FIN in-flight messages?  

I guess the obvious answer is to set the RDY count to 0, finish consuming the queued messages, and then CLS.  Is there a simpler solution (akin to CLS, and cleanup)?  Or should I attempt my RDY count to 0 followed by a series of FINs, and then a CLS?

Thanks for you time.

**Comment by mreiferson** [comment]
> However, I believe that the CLS operation has completely severed the connection to NSQ (so "messages" in the docs means all kinds of NSQ messages, not actual data messages), and those FINs go unreceived.

It doesn't actually close the connection - it effectively does the same thing as manually sending `RDY 0`, i.e. you _can_ continue to respond to messages (`FIN`) after sending `CLS`.  `go-nsq` happens to add a 30 second timer to "force close", just so that the window of time is bounded.

The actual problem here is that a consumer shouldn't have `max_in_flight` set to 2000 if it can only process 1 message per second.  Messages would time out _anyway_ under those conditions.

**Comment by kesutton** [comment]
I was just about to update my question.  The timing of the consumer doesn't really relate to my question specifically, even if messages were responded to instantly, there are still queued messages to handle.

However, it is interesting that you say the connection is still established, and thus FINs are still acknowledged, even after a CLS.  I'm looking at the nsqd logs, and it is flooded with FINs before I stop my test, at which point I see a CLS.  

I'm confirmed that FINs continue to show in the log when I use the:
1. RDY cnt = 0
2. finish consuming messages (at which point messages are FIN'd)
3. CLS
technique.

I understand this could be my own fault in my client library (I'm debugging now), but from what I can see, CLS is basically severing the connection.  I'll try to get a tcp dump or something.

**Comment by mreiferson** [comment]
This is the relevant code for `Consumer.Stop()`, all it does is send the `CLS` command and start a timer:

https://github.com/bitly/go-nsq/blob/master/consumer.go#L1031-L1045

And this is the code on the `nsqd` side to process a `CLS`:

https://github.com/bitly/nsq/blob/master/nsqd/client_v2.go#L382-L387

If you continue to experience problems, can you open up a new issue on https://github.com/bitly/go-nsq?  It's more likely to be useful context there.

Thanks!
