### ISSUE TITLE
Support for logging to Graylog

### ISSUE THREAD

**Issue by sachinwalia2k8** [bitly/nsq#606]
I have started evaluating NSQ recently for our production application. I like it's simplicity so far compared to other messaging platform.

We use graylog for all kinds of application and server logging. One thing I'd like to see in NSQ is support for graylog.

Unfortunately my skills in Go are next to none. Good news is there is already a Go client available for Graylog if someone wants to take a stab at it:

https://github.com/Graylog2/go-gelf

thanks.

**Comment by mreiferson** [comment]
@saichinwalia2k8 thanks for considering NSQ!

I don't foresee us supporting _specific_ logging destinations like graylog directly.  In my brief perusal of the graylog docs, it seems like the best option would be to redirect `nsqd`'s `stderr` to a file or to syslog and ship those logs to graylog via utility processes.

Hope this helps.
