### ISSUE TITLE
SendError: no connections (None)

### ISSUE THREAD

**Issue by kangqiao-lu** [bitly/nsq#607]
writer = nsq.Writer(['127.0.0.1:4150'])
def finish_pub(conn, data):
    print data

def pub_message():
    topic = 'test'
    msg = "it is a test"
    writer.pub(topic=topic, msg=msg, callback=finish_pub)

pub_message()

**Comment by kangqiao-lu** [comment]
I just want wirte nsq once time,do not use tornado.ioloop,some has any idears  ?

**Comment by mreiferson** [comment]
gonna continue this conversation on bitly/pynsq#128
