### ISSUE TITLE
nsqd: shared message access between clients

### ISSUE THREAD

**Issue by zachbadgett** [bitly/nsq#609]
Currently TOUCH, REQ and FIN commands require to be called by the same client; this can potentially limit downstream processing (e.g. separate binaries handling the same message), if one process fails there is no way to requeue and there is no way to 'finish' the message when it's done.

Solutions:
Remove this block:
https://github.com/bitly/nsq/blob/master/nsqd/channel.go#L480:L483
Which would remove the client restriction.

or

Pass in (*clientV2).ClientID instead of ID which would require the Message to hold a string instead of an int64 but would allow access to only specific clients.

**Comment by mreiferson** [comment]
Hi @zachbadgett, I don't follow what you mean by:

> this can potentially limit downstream processing (e.g. separate binaries handling the same message)

Restricting responses to the receiving client was an intentional design decision.  `nsqd` has a message timeout for those that don't receive responses.  The messages are redelivered to another ready client for processing.

**Comment by ploxiln** [comment]
It seems like he wants to pass a message from one consumer process to another consumer process, and have the last consumer finally ack the message when it's done.

The way to do this is for the first consumer to post the message to another topic for the other consumer to subscribe to.

**Comment by zachbadgett** [comment]
@ploxiln you are correct. Sending it back through nsq seems like a lot of extra latency.

As an example I have a set of tools piped together, the message would be consumed through 'nsq_to_stdout' and passed through each app, once it hits 'failapp' I would want to requeue it but since the message belongs to 'nsq_to_stdout' it will produce an error.

```
nsq_to_stdout | app1 | app2 | failapp | app3
```

**Comment by ploxiln** [comment]
If you really wanted to do that, my suggestion would be to write a custom nsq consumer in go or python to "wrap" the pipeline: execute it in a child processes, feed messages into the input pipe, read them from the output pipe, and ack them from the parent, which is the original consumer. You could have multiple in flight at once of course.

But, yeah... nsq is not optimal for that use case, it's for other stuff.

Consider that nsq is designed for scaling: there can be multiple nsqd that have messages for a topic, and a client consumes from all of them. (So passing a message id would not be enough, you'd also need to indicate which nsqd it came from, for the general case.) It's also designed to allow some decoupling between stages, so messages can queue, stages can be scaled independently, etc.

**Comment by zachbadgett** [comment]
Yeah, fair enough. Thanks!
