### ISSUE TITLE
Plugin 'NsqOutput' error: failed to IDENTIFY - write tcp 127.0.0.1:4151: broken pipe

### ISSUE THREAD

**Issue by hejinlong** [bitly/nsq#611]
2015/07/29 15:33:36 Plugin 'NsqOutput' error: failed to IDENTIFY - write tcp 127.0.0.1:4151: broken pipe
2015/07/29 15:33:59 Plugin 'NsqOutput' error: failed to IDENTIFY - unexpected EOF

[NsqOutput]
addresses = ["127.0.0.1:4151"]
topic = "test"
mode = "hostpool"
message_matcher = "TRUE"
encoder = "PayloadEncoder"

**Comment by mreiferson** [comment]
@hejinlong I'm not sure what issue you're actually reporting, but if anything it probably belongs at https://github.com/bitly/go-nsq

Thanks!
