### ISSUE TITLE
Avoid data copy in diskqueue.writeOne()

### ISSUE THREAD

**Issue by xuzhaokui** [bitly/nsq#613]
The code below will make a copy of `data`:

```
	d.writeBuf.Reset()
	err = binary.Write(&d.writeBuf, binary.BigEndian, dataLen)
	if err != nil {
		return err
	}
	_, err = d.writeBuf.Write(data) // copy here
	if err != nil {
		return err
	}
```
This copy can be replaced by a multireader :)

**Comment by xuzhaokui** [comment]
https://github.com/bitly/nsq/pull/614

**Comment by xuzhaokui** [comment]
ready for review ;)

**Comment by chzyer** [comment]
According to the code of `io.MultiReader`, the code using MultiReader is same as follows:
```
d.writeBuf.Write(length)
d.writeBuf.Write(data)
```
WriteBuffer here is a trade-off that reduce the `syscall` and `io write operations` by copying data in one `[]byte`.
May be using two syscall here is much slower than the data copy plus one syscall :)
Anyway, `io.Copy` is another "data copy" way.

**Comment by xuzhaokui** [comment]
@chzyer Got it.

**Comment by mreiferson** [comment]
@chzyer is correct, this was intentional to reduce syscalls
