### ISSUE TITLE
Is there such possibility that the response of the query to nsqlookupd becomes huge,ie 1MB

### ISSUE THREAD

**Issue by lcplj123** [bitly/nsq#630]
consider such sence, million people in the same chatroom, when a stranger cames in, the following steps may take place:
1. make an request to nsqlookupd to get the nsqd instance, in the response of the query,we return the 'channels' data. where  confused me is that in such big chatroom, every one involved should get a channel to a specified topic,does we return all the channels info?Is this necessary?
2. once the stranger connect to nsqd using the union of broadcast_address and tcp_port, i think it's wasteful to communicate with nsqlookupd unless we lost the connection to nsqd instance.

**Comment by jehiah** [comment]
@lcplj123 I appreciate your interest in NSQ. Since this is primarily a design related question in how to solve your use case with NSQ I'm going to close this issue. Can you re-ask this design question on the mailing list? https://groups.google.com/forum/#!forum/nsq-users
