### ISSUE TITLE
how to use nsq_to_file just generate one file per day

### ISSUE THREAD

**Issue by ChengHuaUESTC** [bitly/nsq#638]
When I execute "nsq_to_file --topic=test --output-dir=/tmp --lookupd-http-address=127.0.0.1:4161"
It will generates one file per hour, twenty-four files everyday. Now I just want it to generate one file everyday. I don't find a parameter to work it. How should I do? Is there some suggestions.

**Comment by ploxiln** [comment]
try `--datetime-format="%Y-%m-%d"`. nsq_to_file starts a new file when the effective/evaluated filename changes.

**Comment by ChengHuaUESTC** [comment]
@ploxiln, Your suggestion is effective. I considered it just a parameter to modify file name, but It works. 
nsq_to_file --topic=test --output-dir=/tmp --lookupd-http-address=127.0.0.1:4161 --datetime-format="%Y-%m-%d"
